Adding Unity 2022 / ARF 5 support
realitycollective/com.realitytoolkit.spatial-persistence.asa pull request #8
Opened 2023-08-06 16:31 UTC by SimonDarksideJ

# Reality Collective - Reality Toolkit Pull Request

## Overview

Verified and tested with AR Foundation V5 on Unity 2022

## Changes

Added compiler definitions and alternate code paths for when ARF5 is used, together with the MS ASA components latest

2023-08-07 10:02 UTC, FejZa requested changes

2023-08-07 10:02 UTC, FejZa commented on Runtime/Modules/ASASpatialPersistenceServiceModule.cs
>                          var ARSessionOrigin = GameObject.FindObjectOfType<ARSessionOrigin>();
This could have been just one line of version define code and the rest seems identical and duplicate for both variants.

2023-08-07 10:02 UTC, FejZa commented on Runtime/RealityToolkit.SpatialPersistence.ASA.asmdef
> +            "expression": "[4.6.8]",
Likely it would still work for version below 4.6.8 wouldn't it? This expression nails it down to exactly version 4.6.8 and no other.

2023-08-07 20:26 UTC, SimonDarksideJ commented on Runtime/RealityToolkit.SpatialPersistence.ASA.asmdef
> +            "expression": "[4.6.8]",
Suggestions on updating it? I've effectively only tested with the latest.  The Unity documentation on expressions is "not" very clear.

2023-08-07 20:30 UTC, SimonDarksideJ commented on Runtime/Modules/ASASpatialPersistenceServiceModule.cs
>                          var ARSessionOrigin = GameObject.FindObjectOfType<ARSessionOrigin>();
I think originally I was going to rename the inner property, but either forgot or did not get around to it.
EIther way, you are correct and this has been simplified

2023-08-09 12:26 UTC, SimonDarksideJ commented on Runtime/RealityToolkit.SpatialPersistence.ASA.asmdef
> +            "expression": "[4.6.8]",
Updated pattern to work for any V4 version of ARFoundation

2023-08-09 13:38 UTC, FejZa approved these changes

2023-08-09 13:38 UTC, merged